[project]
name = "stock-trading-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gym-anytrading>=2.0.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "stable-baselines3>=2.7.1",
    "yfinance>=1.2.0",
]
